import{a as p,i as a,S as g}from"./assets/vendor-DYLXiCJH.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f="36828323-5d4b30a68db3a86c330ff5a61",d="https://pixabay.com/api/";function h(s){return p.get(d,{params:{key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>(r.data.hits.length===0&&a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),r.data.hits)).catch(r=>{a.error({title:"Error",message:"Something went wrong. Try again later",position:"topRight"}),console.error("Error: ",r)})}let l;function y(s){const r=document.querySelector(".gallery"),n=s.map(o=>`<a href="${o.largeImageURL}" class="photo-card">
            <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
            <div class="info">
              <p><strong>Likes:</strong> ${o.likes}</p>
              <p><strong>Views:</strong> ${o.views}</p>
              <p><strong>Comments:</strong> ${o.comments}</p>
              <p><strong>Downloads:</strong> ${o.downloads}</p>
            </div>
          </a>`).join("");r.innerHTML=n,l?l.refresh():l=new g(".gallery a",{captionsData:"alt",captionDelay:150,animationSpeed:200,closeText:"×",navText:["<",">"]})}const c=document.querySelector(".search-form"),m=document.querySelector(".gallery"),u=document.querySelector(".loader-wrapper");c.addEventListener("submit",s=>{s.preventDefault();const r=c.searchQuery.value.trim();if(!r){a.warning({message:"Please enter a search query",position:"topRight"});return}m.innerHTML="",u.style.display="flex",h(r).then(n=>{if(n.length===0){a.info({message:"Sorry, there are no images matching your search query",position:"topRight"});return}console.log(n.length),y(n)}).catch(n=>{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",n)}).finally(()=>{c.searchQuery.value="",u.style.display="none"})});
//# sourceMappingURL=index.js.map
