import{a as l,i}from"./assets/vendor-CqoJTpN7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const u="36828323-5d4b30a68db3a86c330ff5a61",g="https://pixabay.com/api/";function p(s){return l.get(g,{params:{key:u,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>(r.data.hits.length===0&&i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),r.data.hits)).catch(r=>{i.error({title:"Error",message:"Something went wrong. Try again later",position:"topRight"}),console.error("Error: ",r)})}function f(s){const r=document.querySelector(".gallery"),n=s.map(o=>`<div class="photo-card">
            <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
            <div class="info">
              <p><strong>Likes:</strong> ${o.likes}</p>
              <p><strong>Views:</strong> ${o.views}</p>
              <p><strong>Comments:</strong> ${o.comments}</p>
              <p><strong>Downloads:</strong> ${o.downloads}</p>
            </div>
          </div>`).join("");r.innerHTML=n}const c=document.querySelector(".search-form"),d=document.querySelector(".gallery");c.addEventListener("submit",s=>{s.preventDefault();const r=c.searchQuery.value.trim();if(!r){i.warning({message:"Please enter a search query",position:"topRight"});return}d.innerHTML="",p(r).then(n=>{if(n.length===0){i.info({message:"Sorry, there are no images matching your search query",position:"topRight"});return}f(n)}).catch(n=>{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",n)}).finally(()=>{c.searchQuery.value=""})});
//# sourceMappingURL=index.js.map
